# /etc/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - /etc/prometheus/rules.yaml
scrape_configs:
  - job_name: node_exporter
    http_sd_configs:
    - url: http://localhost:8090/plugin/Prometheus/target
      refresh_interval: 60s